### ISSUE TITLE
hazelcast client sample json does not work on default cluster

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast-nodejs-client#463]
Is there any reason we gave this sample file different cluster name and password to defaults of `dev` and `dev-pass`.  It won't run out of the box against a default cluster.

https://github.com/hazelcast/hazelcast-nodejs-client/blob/master/hazelcast-client-sample.json

 ```"group": {
        "name": "hazel",
        "password": "cast"
    }
```

**Comment by mustafaiman** [comment]
That file has many invalid lines such as
```
"serializers": [
            {
                "path": "path/to/custom",
                "exportedName": "CustomSerializer1",
                "typeId": 2
            }
        ]
```

It would not work anyway even if we set the default cluster name. The purpose of this file I think was to demonstrate all the available options, rather than serve as a sample. Its name is changed to hazelcast-client-full.json in https://github.com/hazelcast/hazelcast-nodejs-client/pull/465 as it should be. I am closing the issue. If you feel that there must be a "valid and full" configuration file in the repo, please re-open the issue.
