### ISSUE TITLE
Is there a way to register to listen to client events in the cluster

### ISSUE THREAD

**Issue by manoojm** [hazelcast/hazelcast-nodejs-client#485]
Is there a way to register to listen to client events in the cluster? My use-case is that I want to be able to listen to membership listener in the clients. So, whenever a client is disconnected, other clients get notified of the same and can take appropriate remedial action.

Something like this https://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#listening-for-clients

**Comment by puzpuzpuz** [comment]
As described in the documentation, that member API is only available on the cluster-side:
```
The client listener is used by the Hazelcast cluster members. It notifies the cluster member when a client is connected to or disconnected from it, i.e., the clients fire an event from only one member they are connected to.
```

Currently there is no way to listen to such events on the client side. Yet, you could easily implement this functionality via `ReliableTopic`. When a client connects to the cluster, it could send a message to the topic, so that other clients receive it.

**Comment by puzpuzpuz** [comment]
Closing this one as it seems to be answered.
