### ISSUE TITLE
Utility method to check if Map Event Listener is already attached

### ISSUE THREAD

**Issue by sathyarajagopal** [hazelcast/hazelcast-nodejs-client#861]
My hazelcast setup is below:

3 instances of hazelcast nodejs client (per datacenter. Total of 2 DCs resulting in 6 client instances) spun up and connecting to Hazelcast server in a client server architecture.

Requirements: 
I want the mapUpdated event listener to trigger only once. 
If any one of the client instance is down, I want any one of the remaining instances to handle the event rather than event getting lost.

Proposal:
If there is a way that I can find out whether the event listener is already attached, I can do addEntryListener inside that check so that event is not registered and then triggered multiple times.

**Comment by srknzl** [comment]
Hi, @sathyarajagopal 

There is not such a feature right now. Server does not keep track of listeners attached. It would be complex to do so for the server side. We are not planning to add it for now. 

Just to make it clear, a couple of questions:

1. First of all, can you elaborate your use case more? What you are trying to achieve? Relying on listeners for your core application logic is not recommended because during a connectivity problem, all the events sent are lost.  
2. Do you want to add listener only once? So, adding 6 listeners is not ok for you? 
3. Maybe you can move you map usage to queue. In a queue, only one client can consume an entry. 
4. How are you planning to attach a new listener after a client dies?

**Comment by sathyarajagopal** [comment]
> Hi, @sathyarajagopal
> 
> There is not such a feature right now. Server does not keep track of listeners attached. It would be complex to do so for the server side. We are not planning to add it for now.
> 
> Just to make it clear, a couple of questions:
> 
> 1. First of all, can you elaborate your use case more? What you are trying to achieve? Relying on listeners for your core application logic is not recommended because during a connectivity problem, all the events sent are lost.
> 2. Do you want to add listener only once? So, adding 6 listeners is not ok for you?
> 3. Maybe you can move you map usage to queue. In a queue, only one client can consume an entry.
> 4. How are you planning to attach a new listener after a client dies?

@srknzl My apologies for such a long delay. Here are my answers:

Usecase is to have a single client (on a cluster of 3 instances) subscribe to Hazelcast cluster map entry event. Why single client and not all 3 instances is because in the event handler I receive the map updated payload and then persist it to MongoDB. Now, the issue is, if all 3 instances register their handlers, then for a single update in cache, it will result in "n" number of calls to MongoDB, in our case it is 3. To avoid that I was trying to register event only in one instance during the server start by making use of another map and inserting a flag into that map with a ttl of 5 minutes. That was a dirty solution and it has its own flaws. I have now removed all those dirty solutions and instead made it simpler by integrating hazelcast with kafka to achieve what I wanted :)

**Comment by sathyarajagopal** [comment]
@srknzl  Please feel free to close this

**Comment by srknzl** [comment]
Ok glad you solved this, closing
